Fix DOMHTMLSeasonEpisodesParser Rule with key=_seasons
cinemagoer/cinemagoer pull request #503
Opened 2024-02-06 08:44 UTC by mhrashvand1

2024-03-11 14:17 UTC, topongo commented
it still doens't fully work, if you run the tests it still fails: it can find the selected season 'cause they probably changed a bunch of aria-related things. i've already come up with a working solution though

2024-03-23 02:45 UTC, CodeMastr3 requested changes
I believe this might be an easier way to see the requested change 
extractor=Path('//a[@data-testid="tab-season-entry"][contains(@class, "ipc-tab--active")]/text()')

2024-03-23 02:48 UTC, CodeMastr3 commented
@topongo I forked his change and updated line 2164 like you said, and I was having issues with seasons.sort(). Not sure if this is relevant to this issue but at least I was able to grab part of a season with the changes

2024-03-23 09:09 UTC, topongo commented
thanks, I'd do it myself, I just didn't want to make tons of pull requests for just one thing. but seeing the other guy is unresponsive i think it's a good idea.

2024-03-24 13:26 UTC, alberanid commented
hi @CodeMastr3 and @topongo : unfortunately in the last months I had almost zero time to devote to the project.

I'm still willing to do maintenance and help as much as possible and every contribution is welcome. So, please let me know when you are satisfied with the PR and I will merge it.

2024-03-24 22:13 UTC, CodeMastr3 commented
@alberanid So I've used both the current branch for the PR and a branch with the change @topongo recommended but I'm not able to see a difference between them with the small change. It would be nice if @mhrashvand1 returned for this PR
The only thing I know is I'm testing with grabbing One Piece as the series and trying to count all of its episodes but I get back only 50 episodes from season 1 and 11 from season 2 for a total of 61.
I don't know if that is my fault, the fixes fault, or just works this way because on IMDB each series only shows 50 episodes at a time initially

2024-03-26 00:04 UTC, topongo commented
@CodeMastr3
the problem with the 50 episode limit is a web ui problem, already mentioned in #482 and strictly speaking it's unrelated.

i don't know the history of the web ui nor do i know if a recent change broke many things at once... we should ask @alberanid for this. but we should keep this issues separated imo

if @mhrashvand1 won't get in touch in a few days i'll create a new pr

2024-05-15 19:40 UTC, markomno commented
Any plan to merge this PR and build new release with the fix for series seasons and episodes. 
Thanks in advance!

2025-01-20 04:35 UTC, hdantas commented
I couldn't get the series functionality to work with this PR but it led me in the right direction. I've created a [PR](https://github.com/cinemagoer/cinemagoer/pull/524) with an additional fix (and the latest commits from the main).

@CodeMastr3 @topongo  @alberanid please let me know if you'd like additional changes

2025-02-05 21:26 UTC, NS-Coding commented
Is this going to be merged? I cannot grab any episode data at all still.

2025-02-07 08:07 UTC, merged

2025-02-07 08:08 UTC, alberanid commented
merged.

Sorry for the delay, but in the last years I had no time for the project. :'(

2025-02-07 09:39 UTC, markomno commented
Any plans or estimate to publish new release, current available is from 2023, almost two years old?

Thanks and I appreciate your work!

2025-02-09 14:51 UTC, alberanid commented
> Any plans or estimate to publish new release, current available is from 2023, almost two years old?

Doing a release is not a big deal, I can create one if needed.

The problem is that I do not know if it's worth it, since I do not exactly know if any important info is still missing.

I'll try to run the test suite in the next few weeks, and I'll decide what to do.

2025-02-13 18:09 UTC, NS-Coding commented
Seems like the fix isn't working anymore. I cannot grab any episodes. I was able to a week or two, but I no longer can. Did something change?

Thanks for all your work!

2025-03-15 12:46 UTC, Fox214 commented
There's a work around in this thread: https://github.com/cinemagoer/cinemagoer/issues/517#issuecomment-2726498558